name: flutter_share_me
description: Flutter Plugin for sharing contents to social media.You can use it share to Facebook , WhatsApp And System Share UI. Support Url and Text.
version: 1.2.0
homepage: https://github.com/OpenFlutter/flutter_share_me
publish_to: http://pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  # The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: zhuoyuan.li.fluttershareme
        pluginClass: FlutterShareMePlugin
      ios:
        pluginClass: SwiftFlutterShareMePlugin